name: funcubing
description: funcubing app

publish_to: 'none'

version: 1.1.1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  flutter_widget_from_html: ^0.10.0
  spider: ^4.1.0
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  build_runner:

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svgs/
    - assets/translations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.webp"