class Assets {
  Assets._();

  static const String c222 = 'assets/svgs/222.svg';
  static const String c222bf = 'assets/svgs/222bf.svg';
  static const String c234567relay = 'assets/svgs/234567relay.svg';
  static const String c23456relay = 'assets/svgs/23456relay.svg';
  static const String c2345relay = 'assets/svgs/2345relay.svg';
  static const String c234relay = 'assets/svgs/234relay.svg';
  static const String c333 = 'assets/svgs/333.svg';
  static const String c333bf = 'assets/svgs/333bf.svg';
  static const String c333fm = 'assets/svgs/333fm.svg';
  static const String c333ft = 'assets/svgs/333ft.svg';
  static const String c333mbf = 'assets/svgs/333mbf.svg';
  static const String c333mbo = 'assets/svgs/333mbo.svg';
  static const String c333mts = 'assets/svgs/333mts.svg';
  static const String c333oh = 'assets/svgs/333oh.svg';
  static const String c444= 'assets/svgs/444.svg';
  static const String c444bf = 'assets/svgs/444bf.svg';
  static const String c555= 'assets/svgs/555.svg';
  static const String c555bf = 'assets/svgs/555bf.svg';
  static const String c666= 'assets/svgs/666.svg';
  static const String c666bf = 'assets/svgs/666bf.svg';
  static const String c777= 'assets/svgs/777.svg';
  static const String c777bf = 'assets/svgs/777bf.svg';
  static const String clock = 'assets/svgs/clock.svg';
  static const String curvycopter = 'assets/svgs/curvycopter.svg';
  static const String fisher = 'assets/svgs/fisher.svg';
  static const String fto = 'assets/svgs/fto.svg';
  static const String helicopter = 'assets/svgs/helicopter.svg';
  static const String kilominx = 'assets/svgs/kilominx.svg';
  static const String magic = 'assets/svgs/magic.svg';
  static const String miniguild = 'assets/svgs/miniguild.svg';
  static const String minx = 'assets/svgs/minx.svg';
  static const String mmagic = 'assets/svgs/mmagic.svg';
  static const String mpyram = 'assets/svgs/mpyram.svg';
  static const String mskewb = 'assets/svgs/mskewb.svg';
  static const String mtetram = 'assets/svgs/mtetram.svg';
  static const String pyram = 'assets/svgs/pyram.svg';
  static const String pyramorphix = 'assets/svgs/pyramorphix.svg';
  static const String redi = 'assets/svgs/redi.svg';
  static const String skewb = 'assets/svgs/skewb.svg';
  static const String sq1 = 'assets/svgs/sq1.svg';
  static const String vk1 = 'assets/svgs/vk-1.svg';
}
